export const CHURCH_CREATE_REQUEST = "CHURCH_CREATE_REQUEST";
export const CHURCH_CREATE_SUCCESS = "CHURCH_CREATE_SUCCESS";
export const CHURCH_CREATE_FAIL = "CHURCH_CREATE_FAIL";
export const CHURCH_LOGIN_REQUEST = "CHURCH_LOGIN_REQUEST";
export const CHURCH_LOGIN_SUCCESS = "CHURCH_CHURCH_SUCCESS";
export const CHURCH_LOGIN_FAIL = "CHURCH_LOGIN_FAIL";
